### ISSUE TITLE
iOS Build Failed: /SwiftKommunicateFlutterPlugin.swift:39:52 Cannot find 'CustomEvent' in scope

### ISSUE THREAD

**Issue by omarica** [Kommunicate-io/Kommunicate-Flutter-Plugin#128]
Hi, I'm having the below build errors in kommunicate_flutter 1.9.0, would appreciate if you can help.

![image](https://github.com/Kommunicate-io/Kommunicate-Flutter-Plugin/assets/3487160/ee1aa96e-1b10-474e-898b-74965f50c3f5)

![image](https://github.com/Kommunicate-io/Kommunicate-Flutter-Plugin/assets/3487160/b6868c4e-24f8-4f9f-9390-676c8809fc88)

**Comment by AbhijeetRanjan308** [comment]
Hey @omarica , just wanted to let you know that we've rolled out the latest version of Flutter, `kommunicate_flutter: 1.9.1`, which addresses this particular issue. Feel free to give it a try!

**Comment by AbhijeetRanjan308** [comment]
This issue is resolved in `kommunicate_flutter: 1.9.1`.
