### ISSUE TITLE
Error on release

### ISSUE THREAD

**Issue by sudhanshugairola** [Kommunicate-io/Kommunicate-Flutter-Plugin#13]
Note: F:\flutter\.pub-cache\hosted\pub.dartlang.org\kommunicate_flutter_plugin-1.0.9\android\src\main\java\io\kommunicate\kommunicate_flutter_plugin\KommunicateFlutterPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

**Comment by Samir1810** [comment]
@Sudhanshu-Gairola Could you please look if this is an error or warning. Looks like this is a warning, please try this solution and let us know https://stackoverflow.com/questions/57750689/uses-unchecked-or-unsafe-operations-recompile-with-xlintunchecked-for-details

**Comment by Sudhanshu-Gairola** [comment]
ok
another problem is raised when i'm press Talk With Button on live chat page in my flutter project it took time to open live chat view and get late to communicate with server.
any solution for it

**Comment by Samir1810** [comment]
It wouldn't be taking the time. Please provide us with your App ID, Kommunicate SDK version, a video about your issue, and the logs for this issue. Share these details and we shall ask our mobile tech to take a look.

**Comment by deep-esh7** [comment]
it is giving Conversation builder error : PlatformException(Error, {
I/flutter (26290):   "errorResponse": [
I/flutter (26290):     {
I/flutter (26290):       "description": "group already exists",
I/flutter (26290):       "displayMessage": "unable to process",
I/flutter (26290):       "errorCode": "AL-G-02"
I/flutter (26290):     }
I/flutter (26290):   ],
I/flutter (26290):   "generatedAt": "1617098974119",
I/flutter (26290):   "status": "error"
I/flutter (26290): }, null)
I/flutter (26290): Conversation builder error : PlatformException(Error, {
I/flutter (26290):   "errorResponse": [
I/flutter (26290):     {
I/flutter (26290):       "description": "group already exists",
I/flutter (26290):       "displayMessage": "unable to process",
I/flutter (26290):       "errorCode": "AL-G-02"
I/flutter (26290):     }
I/flutter (26290):   ],
I/flutter (26290):   "generatedAt": "1617098974445",
I/flutter (26290):   "status": "error"
I/flutter (26290): }, null)
I/flutter (26290): Conversation builder error : PlatformException(Error, {
I/flutter (26290):   "errorResponse": [
I/flutter (26290):     {
I/flutter (26290):       "description": "group already exists",
I/flutter (26290):       "displayMessage": "unable to process",
I/flutter (26290):       "errorCode": "AL-G-02"
I/flutter (26290):     }
I/flutter (26290):   ],
I/flutter (26290):   "generatedAt": "1617098974860",
I/flutter (26290):   "status": "error"
I/flutter (26290): }, null) this error


with release and not opening what to do??

**Comment by Samir1810** [comment]
What is the sdk version that you are using?
