### ISSUE TITLE
Error flutter build apk --release

### ISSUE THREAD

**Issue by himkhy** [Kommunicate-io/Kommunicate-Flutter-Plugin#14]
Dear team kommunicate support Flutter.
My SDK flutter 1.7.3
I have problem on kommunicate_flutter_plugin: ^1.0.9 when we are build developer in working, But, build for release on command >flutter build apk --release and get App install in Phone app lunch and click on button direct to chat kommunicate it has close app.

Note: Recompile with -Xlint:unchecked for details.

**Comment by Samir1810** [comment]
Hi, 
Could you provide the AppID - You can get from here https://dashboard.kommunicate.io/settings/install, the error logs you're getting while trying in the release, and if it's Android or iOS, share any error screenshots also. Update us with these details.

**Comment by himkhy** [comment]
Thank you for replay

I have found for build release running with chat.

step 1

>> flutter build apk --release

step2

We are need to go open folder Native Android in flutter then build app apk with .jks file and input password jks
