### ISSUE TITLE
On back button pressed event

### ISSUE THREAD

**Issue by AhmedNourJamalElDin** [Kommunicate-io/Kommunicate-Flutter-Plugin#22]
Hi,

I wanted to show the chat as a widget inside a screen. but it seems not possible, right?
so I have changed my mind.

Now I want to know if the chat is closed by pressing the back button or via Android physical back button or anyway. just need to add some code at closing the chatting screen.

How to achieve so?

Thanks

**Comment by Samir1810** [comment]
Hi Ahmed,

>> I wanted to show the chat as a widget inside a screen. 

Could you please explain more about this use-case, inside which screen you mean?

For closing the back buttons would work. Also are you flutter ios or android?

**Comment by AhmedNourJamalElDin** [comment]
Hi hi

> Could you please explain more about this use-case, inside which screen you mean?

I'd like to add some other widgets above or below the chatting widget, perhaps `WillPopScope` to catch back button event. or maybe adding the chat as a main tab in my application.


> For closing the back buttons would work. 

Yes, it does work 100%. but I want to capture the closing event and do some job like logging some event, redirecting, etc.

> Also are you flutter ios or android?

Android for now, but I want to have it working on both of them.

**Comment by Samir1810** [comment]
Hi Ahmed,

Adding our Android developer @reytum  to update your usecase.

**Comment by reytum** [comment]
@AhmedNourJamalElDin As of now we do not provide an option to add the chat screen inside your widget in Flutter. The chat screen will open independently. Also we do no provide an event for the back press of the chat button. One workaround you could use to achieve this is by checking the onResume and onPause events in your screen from where the chat screen is launched. So when the chat is opened, the event fired would be onPause and when you return back from the chat screen, onResume event will be fired. Hope this thread could be helpful: https://stackoverflow.com/questions/49869873/flutter-update-widgets-on-resume

**Comment by AhmedNourJamalElDin** [comment]
Thanks a lot. I will try them.
