### ISSUE TITLE
Not able to add library in the project

### ISSUE THREAD

**Issue by achinverma** [Kommunicate-io/Kommunicate-Flutter-Plugin#23]
Hi,
I am adding this lib in my project. I am getting the below error:
`kommunicate_flutter: ^1.1.2`
```
packages get
Running "flutter pub get" in restroapp...                       
Because restroapp depends on kommunicate_flutter_plugin ^1.1.2 which doesn't match any versions, version solving failed.
pub get failed (1; Because restroapp depends on kommunicate_flutter_plugin ^1.1.2 which doesn't match any versions, version solving failed.) 
```

**Comment by Samir1810** [comment]
Please see if these pre-requisites are met. The Apps using Kommunicate can target Xcode 11 or later and AndroidX is required.

Also is it flutter - android or ios?

**Comment by achinverma** [comment]
Hi, @Samir1810 . It is android.

I have seen all the pre-requisites. All the fine. but i am still getting the error.

**Comment by achinverma** [comment]
issue fixed
