### ISSUE TITLE
Error on Complie Time

### ISSUE THREAD

**Issue by karanSignity** [Kommunicate-io/Kommunicate-Flutter-Plugin#25]
Hi Support Team,

I am facing an issue with compile Time in Xcode.
![Screenshot 2021-01-18 at 3 29 45 PM](https://user-images.githubusercontent.com/59385421/104903237-c2f14600-59a5-11eb-8e07-e0d668cbb34b.png)

**Comment by mukeshthawani** [comment]
Hi can you share the Podfile.lock file to check the details of the dependencies?

**Comment by karanSignity** [comment]
Hi mukesh 

Here Is my pod file

**Comment by mukeshthawani** [comment]
Thanks for sharing. Please upgrade to the latest version of Kommunicate Flutter plugin `1.1.3`, and try again.
