### ISSUE TITLE
update pub dev readme

### ISSUE THREAD

**Issue by obadajasm** [Kommunicate-io/Kommunicate-Flutter-Plugin#3]
i had to  do some modifications to  AndroidManifiest.xml  to make it work 
like adding 
   tools:replace="android:label" inside the application tag 
also adding 
xmlns:tools="http://schemas.android.com/tools" in the manifest tag

AS is it in your example AndroiManifest.xml and i think it`s better if you add this to the pacakge readme section in pub.dev 

keep up the good work 😍

**Comment by reytum** [comment]
@obadajasm We will update the readme. Thanks.

**Comment by omarica** [comment]
I tried, the app builds successfully but the problem with this solution that it crashes the app crashes on Firebase setup on runtime,
I wonder if anybody has a solution that works with firebase?

**Comment by amntoppo** [comment]
Has been added here:
https://docs.kommunicate.io/docs/flutter-troubleshooting
