### ISSUE TITLE
support for null safety

### ISSUE THREAD

**Issue by wangxingxing123654** [Kommunicate-io/Kommunicate-Flutter-Plugin#33]

**Comment by 6h4n3m** [comment]
Any updates on this?

**Comment by Samir1810** [comment]
@6h4n3m Are you trying Kommunicate with Dart 2. Could you explain or you're facing any issues?

**Comment by 6h4n3m** [comment]
> 
> 
> @6h4n3m Are you trying Kommunicate with Dart 2. Could you explain or you're facing any issues?

Yes, I'm using Kommunicate with Flutter 2.0 and Dart 2.12... no issues but the app has to run in mixed mode so I cannot have sound null safety.

**Comment by Samir1810** [comment]
@6h4n3m We have to release a new version with Dart 2 support as it's not compatible, so it will work without sound null safety or add a null check to make it work.

**Comment by ericalderman-emilio** [comment]
When will the Dart 2 version with null safey support be released?

**Comment by Samir1810** [comment]
@ericalderman-emilio We have asked our team for the timeline. Looks like you have requested on chat as well. So, we'll let you know there once we got an update.
