### ISSUE TITLE
unreadCount function always returns 0

### ISSUE THREAD

**Issue by 6h4n3m** [Kommunicate-io/Kommunicate-Flutter-Plugin#49]
`await KommunicateFlutterPlugin.unreadCount();`

Always returns 0, even when there are multiple unread messages.

**Comment by zcabf05** [comment]
This is also an issue with me, any news on fix?

**Comment by amntoppo** [comment]
If you open the conversation using KommunicateFlutterPlugin.openConversation() -> then it sync and starts showing the actual unread messages. In future version, it will be optimized.
