### ISSUE TITLE
The app crash on the release version

### ISSUE THREAD

**Issue by AmoJava** [Kommunicate-io/Kommunicate-Flutter-Plugin#6]
the plugin work well in debug mode but in the release build the app stop on loading  the chat

**Comment by reytum** [comment]
@AmoJava Could you please share some crash logs. It might be issue with proguard. You can try adding the proguard rules in your proguard-rules.pro file. These are the rules used by KM SDK: https://docs.kommunicate.io/docs/android-installation.html#building-with-proguard

**Comment by AmoJava** [comment]
thanks reytum
The problem was really because of the proguard-rules 
and it solved by adding the proguard file inside 
"android" >"app" folder 
and adjust the buildTypes 
to this 
` buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release

        }
    } `
