### ISSUE TITLE
Unable to send message from iOS flutter app to bot

### ISSUE THREAD

**Issue by rish07** [Kommunicate-io/Kommunicate-Flutter-Plugin#68]
Hey,

I am trying to integrate my Kommunicate bot with the flutter app. The integration works fine on android but on iOS I am not able to send any messages from the app to the bot. 

As soon as i press `Send Chat` inside the bot, it prints:

```
current indexpath: 4 and tableview section 4
Cell updated at row:  0 and type is:  text
[unspecified] 
container_create_or_lookup_app_group_path_by_app_group_identifier: client 
is not entitled
[unspecified] 
container_create_or_lookup_app_group_path_by_app_group_identifier: client 
is not entitled
[unspecified] 
container_create_or_lookup_app_group_path_by_app_group_identifier: client 
is not entitled
[unspecified] 
container_create_or_lookup_app_group_path_by_app_group_identifier: client 
is not entitled
[unspecified] 
container_create_or_lookup_app_group_path_by_app_group_identifier: client 
is not entitled
[unspecified] 
container_create_or_lookup_app_group_path_by_app_group_identifier: client 
is not entitled
[unspecified] 
container_create_or_lookup_app_group_path_by_app_group_identifier: client 
is not entitled
Message sent section: 4, Optional("No")

```
Also looks like this inside the app:
![IMG_579674360EC3-1](https://user-images.githubusercontent.com/49035175/196681075-3eb10b9f-4d27-4be8-9283-07f9399fa03c.jpeg)

I am using `kommunicate_flutter: ^1.5.0` and testing on iPhone 11 on iOS 16.0.3

Please help.

**Comment by Sathyan-Elangovan** [comment]
@rish07 We are checking it in our end..We will update you ASAP

**Comment by amntoppoKM** [comment]
@rish07 can you share the code you are using?

**Comment by Sathyan-KM** [comment]
Closing this issue as there is no update from you @rish07
