### ISSUE TITLE
Chat breaks when build for release

### ISSUE THREAD

**Issue by xbassols** [Kommunicate-io/Kommunicate-Flutter-Plugin#8]
Hello,

When we run the app in development it works fine but when we build for release and then test it when we try to open the chat the app breaks.

Do you have suggestion on what could be happening?

Latest android version, Pixel 4.
Tested with 'com.google.gms:google-services:3.1.1' and classpath 'com.google.gms:google-services:4.3.0'

Best,

**Comment by Samir1810** [comment]
Hi,

>> when we try to open the chat the app breaks.
Could you explain this issue in detail? Also provide us with the error logs, error screenshot, or a video explaining this issue from where you're getting the error.

Please share all the details, so it will be easy for us to debug and then we'll ask our expert to check further. Awaiting your reply.

**Comment by devashishmamgain** [comment]
@xbassols whats the meaning of 'breaks' here? Are you seeing any screen which says contact support or is there any error coming in logs?

**Comment by Samir1810** [comment]
Hi,

Could you explain this "when we try to open the chat the app breaks." in detail, from where you're getting this error. Also share the error logs, error screenshot or video explaining the issue. Please provide the details and so we can debug further

**Comment by xbassols** [comment]
Sorry I'll try to explain a little better.

When on debug we reach this lines and it works as it should. It opens the chat screen and all.

```
dynamic conversationObject = {
        'appId': Utils.chatAppId,
        'isUnique': true,
        'kmUser': jsonEncode(user),
        'metadata': {
          'userId' : '${UserManager.user.id}',
          'firstName' : UserManager.user.firstName,
          'lastName' : UserManager.user.lastName,
        }
      };

dynamic result = await KommunicateFlutterPlugin.buildConversation(conversationObject);
```
The problem is when we build the app for release (flutter build apk --release or flutter build ios --release). Then when we try to open the chat screen the app just closes. Since it is a release build the logs are much less explicit so I don't really know what is going on.

```
java.lang.IllegalStateException: Reply already submitted
        at io.flutter.embedding.engine.a.c$a.a(:4)
        at f.b.a.a.l.a(:2)
        at f.c.e.a.b(:1)
        at f.c.i.a(:9)
        at f.c.p.a(:5)
        at f.c.a.m.a(:17)
        at f.c.a.m.onPostExecute(:1)
        at android.os.AsyncTask.finish(AsyncTask.java:755)
        at android.os.AsyncTask.access$900(AsyncTask.java:192)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

It breaks in Android and in iOS.
We tested on multiple phones.

**Comment by Samir1810** [comment]
@xbassols Thanks for sharing the details. I shall ask one of our experts to take a look and update you.

**Comment by reytum** [comment]
@xbassols It might be because you are building with proguard enabled. You can add the below rules in `proguard-rules.pro` file:

```
  #keep JSON classes                
-keep class * extends com.applozic.mobicommons.json.JsonMarker {
    !static !transient <fields>;
}

-keepclassmembernames class * extends com.applozic.mobicommons.json.JsonParcelableMarker {
    !static !transient <fields>;
}

#GSON Config          
-keepattributes Signature          
-keep class sun.misc.Unsafe { *; }           
-keep class com.google.gson.examples.android.model.** { *; }            
-keep class org.eclipse.paho.client.mqttv3.logging.JSR47Logger { *; } 
-keep class android.support.** { *; }
-keep interface android.support.** { *; }
-dontwarn android.support.v4.**
-keep public class com.google.android.gms.* { public *; }
-dontwarn com.google.android.gms.**
-keep class com.google.gson.** { *; }
```

**Comment by xbassols** [comment]
I have it disabled plus it happens also on iOS and proguard does not apply there.

**Comment by reytum** [comment]
@xbassols Try it once by adding the proguard rules. The crash you have shared does not provide sufficient information.
