### ISSUE TITLE
Flutter run error AndoridManifest

### ISSUE THREAD

**Issue by addreeh** [Kommunicate-io/Kommunicate-Flutter-Plugin#97]
I tried to launch my application with the latest plugin version and I get this error:
`C:\Users\Administrator\Desktop\flutter\tgpersonalcloud\android\app\src\debug\AndroidManifest.xml Error:
        Attribute application@label value=(TGPersonalCloud) from (unknown)
        is also present at [io.kommunicate.sdk:kommunicateui:2.8.0] AndroidManifest.xml:21:9-41 value=(@string/app_name).
        Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:9:5-41:19 to override.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed : Attribute application@label value=(TGPersonalCloud) from (unknown)
        is also present at [io.kommunicate.sdk:kommunicateui:2.8.0] AndroidManifest.xml:21:9-41 value=(@string/app_name).
        Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:9:5-41:19 to override.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Running Gradle task 'assembleDebug'...                              3,2s
Exception: Gradle task assembleDebug failed with exit code 1`

I also tried to add the tools:replace line and i get this other error:
`
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> com.android.manifmerger.ManifestMerger2$MergeFailureException: Error parsing C:\Users\Administrator\Desktop\flutter\tgpersonalcloud\android\app\src\main\AndroidManifest.xml

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Running Gradle task 'assembleDebug'...                              3,1s
Exception: Gradle task assembleDebug failed with exit code 1`

**Comment by pranaysaini04** [comment]
@addreeh its happening because of the "label" attribute is also defined in our SDK.Try to 'tools:replace="android:label".  attribute to the application element in your AndroidManifest.xml file.

**Comment by pranaysaini04** [comment]
@addreeh can you share your AndroidManifest code

**Comment by pranaysaini04** [comment]
which gradle version you are using?

**Comment by pranaysaini04** [comment]
@addreeh try to add this line '<manifest xmlns:tools="http://schemas.android.com/tools">' under manifest element

**Comment by pranaysaini04** [comment]
@addreeh 
<img width="827" alt="Screenshot 2023-10-01 at 3 00 07 PM" src="https://github.com/Kommunicate-io/Kommunicate-Flutter-Plugin/assets/128575315/34496055-aa29-41df-8934-e17bd55eebad">


Like this

**Comment by pranaysaini04** [comment]
You can call buildConversation method of kommunicate in the onPressed()

**Comment by pranaysaini04** [comment]
@addreeh that above crash temporary. Fix is to add that applozic-settings.json file, in the upcoming release it will be fixed and you will not be required to add that customisation file

**Comment by pranaysaini04** [comment]
@addreeh which colour customisation are you trying to do,And are you creating new user everytime when build conversation method is called?
